### ISSUE TITLE
The app got crashed when launching on android phone

### ISSUE THREAD

**Issue by cindyha** [AhsanAyaz/flutter_contacts_list#2] opened 2020-04-29 09:48 UTC
Hi!
I'm having an issue when trying to build the app on android. This is the log:

Launching lib\main.dart on Nokia 7 2 in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        17.5s
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                         4.8s
D/FlutterActivity(23291): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(23291): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(23291): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate(23291): Attaching FlutterEngine to the Activity that owns this Fragment.
D/FlutterView(23291): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@78b24b1
D/FlutterActivityAndFragmentDelegate(23291): Executing Dart entrypoint: main, and sending initial route: /
E/AndroidRuntime(23291): FATAL EXCEPTION: pool-2-thread-1               
E/AndroidRuntime(23291): Process: com.example.contacts_app, PID: 23291
E/AndroidRuntime(23291): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(23291):        at android.os.AsyncTask$4.done(AsyncTask.java:399)
E/AndroidRuntime(23291):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(23291):        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(23291):        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(23291):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(23291):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(23291):        at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(23291): Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{37be599 23291:com.example.contacts_app/u0a223} (pid=23291, uid=10223) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
E/AndroidRuntime(23291):        at android.os.Parcel.createException(Parcel.java:2071)
E/AndroidRuntime(23291):        at android.os.Parcel.readException(Parcel.java:2039)
E/AndroidRuntime(23291):        at android.os.Parcel.readException(Parcel.java:1987)
E/AndroidRuntime(23291):        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5054)
E/AndroidRuntime(23291):        at android.app.ActivityThread.acquireProvider(ActivityThread.java:6602)
E/AndroidRuntime(23291):        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2725)
E/AndroidRuntime(23291):        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2120)
E/AndroidRuntime(23291):        at android.content.ContentResolver.query(ContentResolver.java:930)
E/AndroidRuntime(23291):        at android.content.ContentResolver.query(ContentResolver.java:881)
E/AndroidRuntime(23291):        at android.content.ContentResolver.query(ContentResolver.java:837)
E/AndroidRuntime(23291):        at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin.getCursor(ContactsServicePlugin.java:229)
E/AndroidRuntime(23291):        at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin.access$200(ContactsServicePlugin.java:44)
E/AndroidRuntime(23291):        at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground(ContactsServicePlugin.java:170)
E/AndroidRuntime(23291):        at flutter.plugins.contactsservice.contactsservice.ContactsServicePlugin$GetContactsTask.doInBackground(ContactsServicePlugin.java:149)
E/AndroidRuntime(23291):        at android.os.AsyncTask$3.call(AsyncTask.java:378)
E/AndroidRuntime(23291):        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(23291):        ... 3 more
E/AndroidRuntime(23291): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(23291):        at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:6954)   
E/AndroidRuntime(23291):        at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7374)       
E/AndroidRuntime(23291):        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2078)
E/AndroidRuntime(23291):        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2765)
E/AndroidRuntime(23291):        at android.os.Binder.execTransactInternal(Binder.java:1021)
E/AndroidRuntime(23291):
Lost connection to device.
I/Process (23291): Sending signal. PID: 23291 SIG: 9
Syncing files to device Nokia 7 2...
Could not update files on device: HttpException: Connection closed before full header was received, uri =
http://127.0.0.1:53042/7bMByz4HsY4=/
Syncing files to device Nokia 7 2...

**Comment by AntonyLeons** [comment] 2020-08-12 22:39
Hi, 

So I also ran into this issue. The problem is the fact contact permissions are not requested in the app and therefore it is a hard crash.

Enabling permissions and relaunching fixes this.

I may open a pull request to add a request permissions.

**Comment by AhsanAyaz** [comment] 2020-08-15 19:06
Hey @cindyha,
As @AntonyLeons mentioned. The issue was fixed with the PR.
I also fixed other issues mentioned by @AntonyLeons in his PR. Should be good to go. 
Please re-open the issue if it persists still.

**Closed as completed by AhsanAyaz** 2020-08-15 19:06 UTC
